import type { Metadata } from "next";
import { Archivo} from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} antialiased`}
      >
        <StoreProvider>

          <div className="min-h-screen flex flex-col">
            <main className="flex-grow">{children}</main>
            {/* <Footer /> */}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
